// <auto-generated />
using System;
using CMOmeets.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMOmeets.Domain.Data.Migrations
{
    [DbContext(typeof(CmoMeetsDbContext))]
    [Migration("20260525155235_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMOmeets.Domain.Entities.DepartmentMa", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("createdBy");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("departmentName");

                    b.Property<string>("DepartmentNameHin")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("departmentNameHin");

                    b.Property<int?>("MinistryId")
                        .HasColumnType("int")
                        .HasColumnName("ministryID");

                    b.HasKey("Rid");

                    b.HasIndex("MinistryId");

                    b.ToTable("departmentMas", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.DesignationMa", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("createdBy");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("designationName");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobileNo");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("officerName");

                    b.Property<int?>("SeqNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(9999)
                        .HasColumnName("seqNo");

                    b.HasKey("Rid");

                    b.ToTable("designationMas", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.LoginHistoryPwd", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("AuthId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AuthID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IpAdd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_add");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("logout_time");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("session_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userType");

                    b.HasKey("Rid");

                    b.ToTable("login_history_pwd", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MasDeptDesignation", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("createdBy");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("deptID");

                    b.Property<string>("DesigName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("desigName");

                    b.Property<int>("SeqNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(9)
                        .HasColumnName("seqNo");

                    b.HasKey("Rid")
                        .HasName("PK_MAS_DeptDesignation_RID");

                    b.HasIndex("DeptId");

                    b.ToTable("MAS_DeptDesignation", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MasterDistrict", b =>
                {
                    b.Property<string>("DCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dCode");

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dName");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("isActive")
                        .IsFixedLength();

                    b.HasKey("DCode");

                    b.ToTable("Master_District", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MinistryMa", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MinistryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("ministryName");

                    b.HasKey("Rid");

                    b.ToTable("ministryMas", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingAgenda", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"));

                    b.Property<string>("Active")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active")
                        .IsFixedLength();

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addedBy");

                    b.Property<DateOnly?>("AgendaDueDt")
                        .HasColumnType("date")
                        .HasColumnName("agendaDueDt");

                    b.Property<string>("AgendaMembers")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("agendaMembers");

                    b.Property<string>("AgendaStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("InProgress")
                        .HasColumnName("agendaStatus");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("State")
                        .HasColumnName("districtName");

                    b.Property<string>("MeetingAgenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meetingAgenda");

                    b.Property<int>("MeetingRid")
                        .HasColumnType("int")
                        .HasColumnName("meetingRID");

                    b.Property<string>("MemberRids")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("memberRIDs");

                    b.HasKey("Rid")
                        .HasName("PK__tb_meeti__CAFF413277474227");

                    b.HasIndex("MeetingRid");

                    b.ToTable("tb_meetingAgendas", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingGroup", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addedBy");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("groupName");

                    b.HasKey("Rid");

                    b.ToTable("tb_MeetingGroup", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingMappedGroup", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addedBy");

                    b.Property<long>("GroupRid")
                        .HasColumnType("bigint")
                        .HasColumnName("groupRID");

                    b.Property<int>("MeetingRid")
                        .HasColumnType("int")
                        .HasColumnName("meetingRID");

                    b.HasKey("Rid")
                        .HasName("PK_tb_meetingMappedGroup_RID");

                    b.HasIndex("GroupRid");

                    b.HasIndex("MeetingRid");

                    b.ToTable("tb_meetingMappedGroup", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingMember", b =>
                {
                    b.Property<int>("MeetingRid")
                        .HasColumnType("int")
                        .HasColumnName("meetingRID");

                    b.Property<int>("MemberRid")
                        .HasColumnType("int")
                        .HasColumnName("memberRID");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MeetingRid", "MemberRid");

                    b.HasIndex("MemberRid");

                    b.ToTable("tb_meetingMembers", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingSchedule", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addedBy");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("meetingDate");

                    b.Property<string>("MeetingDocument")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("meetingDocument");

                    b.Property<string>("MeetingPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("meetingPlace");

                    b.Property<string>("MeetingSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("meetingSubject");

                    b.HasKey("Rid")
                        .HasName("PK__tb_meeti__CAFF4132428AB66A");

                    b.ToTable("tb_meetingSchedules", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbRemarksOnAgenda", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addedBy");

                    b.Property<DateOnly?>("AgendaDueDate")
                        .HasColumnType("date")
                        .HasColumnName("agendaDueDate");

                    b.Property<string>("AgendaRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agendaRemarks");

                    b.Property<long>("AgendaRid")
                        .HasColumnType("bigint")
                        .HasColumnName("agendaRID");

                    b.Property<string>("AtrDoc")
                        .HasMaxLength(350)
                        .IsUnicode(false)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("atrDoc");

                    b.Property<int>("MeetingRid")
                        .HasColumnType("int")
                        .HasColumnName("meetingRID");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("memberName");

                    b.Property<int>("MemberRid")
                        .HasColumnType("int")
                        .HasColumnName("memberRID");

                    b.Property<string>("RemarkStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("remarkStatus");

                    b.Property<DateOnly?>("RemarksDate")
                        .HasColumnType("date")
                        .HasColumnName("remarksDate");

                    b.HasKey("Rid");

                    b.HasIndex("AgendaRid");

                    b.HasIndex("MeetingRid");

                    b.ToTable("tb_remarksOnAgendas", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TblOfficer", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .HasColumnName("active")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("createdBy");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("deptID");

                    b.Property<int>("DesigId")
                        .HasColumnType("int")
                        .HasColumnName("desigID");

                    b.Property<string>("OfficerMobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("officerMobile");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("officerName");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("updatedBy");

                    b.HasKey("Rid");

                    b.HasIndex("DeptId");

                    b.HasIndex("DesigId");

                    b.ToTable("tbl_Officers", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.UserAuthenticationDetail", b =>
                {
                    b.Property<string>("AuthId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AuthID");

                    b.Property<string>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("Y")
                        .IsFixedLength();

                    b.Property<string>("AuthPwd")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AuthId")
                        .HasName("PK__User_Aut__12C15D338E8E35CE");

                    b.ToTable("User_Authentication_Detail", (string)null);
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.DepartmentMa", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.MinistryMa", "Ministry")
                        .WithMany("DepartmentMas")
                        .HasForeignKey("MinistryId")
                        .HasConstraintName("FK_departmentMas_ministry");

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MasDeptDesignation", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.DepartmentMa", "Dept")
                        .WithMany("MasDeptDesignations")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_deptDesig_department");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingAgenda", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingSchedule", "MeetingR")
                        .WithMany("TbMeetingAgenda")
                        .HasForeignKey("MeetingRid")
                        .IsRequired()
                        .HasConstraintName("FK_agenda_schedule");

                    b.Navigation("MeetingR");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingMappedGroup", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingGroup", "GroupR")
                        .WithMany("TbMeetingMappedGroups")
                        .HasForeignKey("GroupRid")
                        .IsRequired()
                        .HasConstraintName("FK_mappedGroup_group");

                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingSchedule", "MeetingR")
                        .WithMany("TbMeetingMappedGroups")
                        .HasForeignKey("MeetingRid")
                        .IsRequired()
                        .HasConstraintName("FK_mappedGroup_schedule");

                    b.Navigation("GroupR");

                    b.Navigation("MeetingR");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingMember", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingSchedule", "MeetingR")
                        .WithMany("TbMeetingMembers")
                        .HasForeignKey("MeetingRid")
                        .IsRequired()
                        .HasConstraintName("FK_members_schedule");

                    b.HasOne("CMOmeets.Domain.Entities.TblOfficer", "MemberR")
                        .WithMany("TbMeetingMembers")
                        .HasForeignKey("MemberRid")
                        .IsRequired()
                        .HasConstraintName("FK_members_officer");

                    b.Navigation("MeetingR");

                    b.Navigation("MemberR");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbRemarksOnAgenda", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingAgenda", "AgendaR")
                        .WithMany("TbRemarksOnAgenda")
                        .HasForeignKey("AgendaRid")
                        .IsRequired()
                        .HasConstraintName("FK_remarks_agenda");

                    b.HasOne("CMOmeets.Domain.Entities.TbMeetingSchedule", "MeetingR")
                        .WithMany("TbRemarksOnAgenda")
                        .HasForeignKey("MeetingRid")
                        .IsRequired()
                        .HasConstraintName("FK_remarks_schedule");

                    b.Navigation("AgendaR");

                    b.Navigation("MeetingR");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TblOfficer", b =>
                {
                    b.HasOne("CMOmeets.Domain.Entities.DepartmentMa", "Dept")
                        .WithMany("TblOfficers")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_officers_department");

                    b.HasOne("CMOmeets.Domain.Entities.MasDeptDesignation", "Desig")
                        .WithMany("TblOfficers")
                        .HasForeignKey("DesigId")
                        .IsRequired()
                        .HasConstraintName("FK_officers_deptDesig");

                    b.Navigation("Dept");

                    b.Navigation("Desig");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.DepartmentMa", b =>
                {
                    b.Navigation("MasDeptDesignations");

                    b.Navigation("TblOfficers");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MasDeptDesignation", b =>
                {
                    b.Navigation("TblOfficers");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.MinistryMa", b =>
                {
                    b.Navigation("DepartmentMas");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingAgenda", b =>
                {
                    b.Navigation("TbRemarksOnAgenda");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingGroup", b =>
                {
                    b.Navigation("TbMeetingMappedGroups");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TbMeetingSchedule", b =>
                {
                    b.Navigation("TbMeetingAgenda");

                    b.Navigation("TbMeetingMappedGroups");

                    b.Navigation("TbMeetingMembers");

                    b.Navigation("TbRemarksOnAgenda");
                });

            modelBuilder.Entity("CMOmeets.Domain.Entities.TblOfficer", b =>
                {
                    b.Navigation("TbMeetingMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
